type KeyNamesTypes = {
    [key: string]: string;
}

const keyNames: KeyNamesTypes = {
        'Escape': 'ESC',
        'F1': 'F1',
        'F2': 'F2',
        'F3': 'F3',
        'F4': 'F',
        'F5': 'F5',
        'F6': 'F6',
        'F7': 'F7',
        'F8': 'F8',
        'F9': 'F9',
        'F10': 'F10',
        'F11': 'F11',
        'F12': 'F12',
        'Backquote': '`',
        'Digit1': '1',
        'Digit2': '2',
        'Digit3': '3',
        'Digit4': '4',
        'Digit5': '5',
        'Digit6': '6',
        'Digit7': '7',
        'Digit8': '8',
        'Digit9': '9',
        'Digit0': '0',
        'Minus': '-',
        'Equal': '=',
        'Backspace': 'Backspace',
        'Tab': 'Tab',
        'KeyQ': 'Q',
        'KeyW': 'W',
        'KeyE': 'E',
        'KeyR': 'R',
        'KeyT': 'T',
        'KeyY': 'Y',
        'KeyU': 'U',
        'KeyI': 'I',
        'KeyO': 'O',
        'KeyP': 'P',
        'BracketLeft': '[',
        'BracketRight': ']',
        'Backslash': '\\',
        'CapsLock': 'CapsLock',
        'KeyA': 'A',
        'KeyS': 'S',
        'KeyD': 'D',
        'KeyF': 'F',
        'KeyG': 'G',
        'KeyH': 'H',
        'KeyJ': 'J',
        'KeyK': 'K',
        'KeyL': 'L',
        'Semicolon': ';',
        'Quote': '\'',
        'Enter': 'Enter',
        'ShiftLeft': 'L.Shift',
        'KeyZ': 'Z',
        'KeyX': 'X',
        'KeyC': 'C',
        'KeyV': 'V',
        'KeyB': 'B',
        'KeyN': 'N',
        'KeyM': 'M',
        'Comma': ',',
        'Period': '.',
        'Slash': '/',
        'ShiftRight': 'R.Shift',
        'ControlLeft': 'L.Ctrl',
        'MetaLeft': 'Win',
        'AltLeft': 'L.Alt',
        'Space': 'SpaceBar',
        'AltRight': 'R.Alt',
        'ContextMenu': 'ContextMenu',
        'ControlRight': 'R.Ctrl',
        'PrintScreen': 'PrintScreen',
        'ScrollLock':'ScrollLock',
        'Pause': 'Pause',
        'Insert': 'Insert',
        'Home': 'Home',
        'PageUp': 'PageUp',
        'Delete': 'Delete',
        'End': 'End',
        'PageDown': 'PageDown',
        'ArrowUp': 'Up',
        'ArrowLeft': 'Left',
        'ArrowDown':'Down',
        'ArrowRight':'Right',
}

export const getKeyName = (code: string): string => {
    return keyNames[code];
}